/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_appsync_graphqlEndpoint": "https://kwo2zova2rfdzk3qefidtkd77e.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fgx6mdluuzb73fiscvrbwyitca",
    "aws_cognito_identity_pool_id": "us-west-1:fcc67ddf-130d-463f-8c44-c45f0230cc29",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_kPV5DtSze",
    "aws_user_pools_web_client_id": "2fvkvfsk4uoq1l2efpao1uqho4",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
